### ISSUE TITLE
[BUG] Validação de Token no Payload e Ajuste nos Retornos de Erros da API

### ISSUE THREAD

**Issue by htamagnus** [Quest-Finder/temvagamestre.server#74]
### Problema Identificado:

Durante o processo de homologação, QA estava com problema para testar uma rota pois estava usando sempre o mesmo token para a requisição e gerava um erro 500, nisso notei um problema relacionado à validação de tokens já utilizados e ao gerenciamento da duração e reutilização dos tokens. Especificamente:

- **Validação do Payload (falha de segurança):**
        Há necessidade de verificar se o e-mail dentro do payload do token corresponde ao e-mail (id ou ao dado usado pra validar) que está sendo enviado no payload. Se não houver correspondência, isso pode abrir uma brecha de segurança, permitindo que um token válido de outro e-mail seja reutilizado.

 - **Reutilização de Tokens:**
        O token está sendo reutilizado indevidamente, o que causou problemas durante a homologação. A solução proposta é adicionar uma validação que faça um throw de erro quando o token já foi utilizado, retornando a mensagem apropriada para evitar confusão.

- **Duração do Token:**
        Sugeri a possibilidade de diminuir o tempo de duração do token, ou/e permitir que o token seja utilizado para várias requisições, aumentando seu tempo de expiração para 1 dia.

---

### Melhorias Propostas:

- **Correção da Validação:** 
Implementar a verificação do payload para garantir que o e-mail no token corresponde ao e-mail no payload. Caso contrário, retornar um erro de segurança.

- **Throw para Tokens Usados:** 
Adicionar uma verificação para impedir a reutilização de tokens já utilizados, retornando uma mensagem de erro específica.

- **Ajuste na Duração do Token:** 
Implementar uma configuração para diminuir o tempo de duração do token ou permitir múltiplas requisições dentro de um prazo determinado (por exemplo, 1 dia).

---

### Retornos de Erros da API

Além disso, foi identificado que os retornos de erros da API não seguem um padrão adequado. Sugestão:

Adotar o padrão de erro REST RFC para melhorar a clareza e consistência dos erros retornados.

**Comment by htamagnus** [comment]
### Sugestão REST RFC: 
(fiz de uma maneira simples e rápida, da pra melhorar)

```
class ValidationError extends Error {
  constructor(title, detail, status, instance) {
    super(detail);
    this.title = title; 
    this.status = status;
    this.instance = instance;
    this.type = "path/to/endpoint";
  }

  toJSON() {
    return {
      type: this.type,
      title: this.title,
      status: this.status,
      detail: this.message,
      instance: this.instance,
    };
  }
}
```


### Uso: 
```
    throw new ValidationError(
      "Invalid Token",
      "The provided token does not match the expected email address.",
      400,
      "/path/to/resource" // Instância do erro (pode ser o endpoint ou algo que identifique a ocorrência)
    )
```

**Comment by felipesouza91** [comment]
@htamagnus , atualizei a branch, com o ajuste porem realizando essa analise, observei que não da para validar somente pelo usuário, pois o quando o cleck devolve os dados para o nosso webhook para salvar o usuário para gente, ele já cadastrada o user no bando de dados, com isso não é tão valido validar somente a utilização do token para ver se ele já foi cadastrado, pois  o token, vem como o id do usuário que já foi cadastrado pelo cleack no seu webhook. Com isso o teste adicional que eu fiz foi validar se o usarname do usuário já esta cadastrado se esse username já esta cadastrado então o token já foi utilizado e com isso da um execption.  

Como comentei fiz a implementação validando o usarname, porem minha recomendação seria também deixar esse username obrigatório para o cadastro, pois asssim a validação do token se torna valida.
